export const FETCH_TREND_GIF_BEGIN = "FETCH_TREND_GIF_BEGIN";
export const FETCH_TREND_GIF_SUCCESS = "FETCH_TREND_GIF_SUCCESS";
export const FETCH_MORE_GIF_BEGIN = "FETCH_MORE_GIF_BEGIN";
export const FETCH_MORE_GIF_SUCCESS = "FETCH_MORE_GIF_SUCCESS";
export const FETCH_SEARCH_GIF_SUCCESS = "FETCH_SEARCH_GIF_SUCCESS";
export const FIRST_SCROLL_FETCH = "FIRST_SCROLL_FETCH";
export const FETCH_TREND_GIF_FAILURE = "FETCH_TREND_GIF_FAILURE";



